"""Pydantic schemas package."""
from app.schemas.program import (
    GoalWeight,
    HybridDefinition,
    HybridDayDefinition,
    HybridBlockComposition,
    MovementRuleCreate,
    EnjoyableActivityCreate,
    ProgramCreate,
    ProgramResponse,
    MicrocycleResponse,
    ExerciseBlock,
    FinisherBlock,
    SessionResponse,
    ProgramWithMicrocycleResponse,
)
from app.schemas.daily import (
    DailyPlanRequest,
    DailyPlanResponse,
    SorenessInput,
    RecoveryInput,
    AdaptationRequest,
    AdaptedSessionPlan,
    AdaptationResponse,
    ConversationTurnResponse,
    ConversationThreadResponse,
    AcceptPlanRequest,
    AcceptPlanResponse,
)
from app.schemas.logging import (
    TopSetCreate,
    TopSetResponse,
    WorkoutLogCreate,
    WorkoutLogResponse,
    WorkoutLogSummary,
    SorenessLogCreate,
    SorenessLogResponse,
    RecoverySignalCreate,
    RecoverySignalResponse,
    PatternPSIResponse,
    ProgressSummaryResponse,
)
from app.schemas.settings import (
    UserSettingsUpdate,
    UserSettingsResponse,
    UserProfileUpdate,
    UserProfileResponse,
    MovementResponse,
    MovementListResponse,
    HeuristicConfigCreate,
    HeuristicConfigResponse,
    HeuristicConfigListResponse,
    ActivateConfigRequest,
    MovementRuleResponse,
    MovementRuleCreate as SettingsMovementRuleCreate,
    MovementRuleUpdate,
    EnjoyableActivityResponse,
    EnjoyableActivityCreate as SettingsEnjoyableActivityCreate,
    EnjoyableActivityUpdate,
)

__all__ = [
    # Program schemas
    "GoalWeight",
    "HybridDefinition",
    "HybridDayDefinition",
    "HybridBlockComposition",
    "MovementRuleCreate",
    "EnjoyableActivityCreate",
    "ProgramCreate",
    "ProgramResponse",
    "MicrocycleResponse",
    "ExerciseBlock",
    "FinisherBlock",
    "SessionResponse",
    "ProgramWithMicrocycleResponse",
    # Daily schemas
    "DailyPlanRequest",
    "DailyPlanResponse",
    "SorenessInput",
    "RecoveryInput",
    "AdaptationRequest",
    "AdaptedSessionPlan",
    "AdaptationResponse",
    "ConversationTurnResponse",
    "ConversationThreadResponse",
    "AcceptPlanRequest",
    "AcceptPlanResponse",
    # Logging schemas
    "TopSetCreate",
    "TopSetResponse",
    "WorkoutLogCreate",
    "WorkoutLogResponse",
    "WorkoutLogSummary",
    "SorenessLogCreate",
    "SorenessLogResponse",
    "RecoverySignalCreate",
    "RecoverySignalResponse",
    "PatternPSIResponse",
    "ProgressSummaryResponse",
    # Settings schemas
    "UserSettingsUpdate",
    "UserSettingsResponse",
    "UserProfileUpdate",
    "UserProfileResponse",
    "MovementResponse",
    "MovementListResponse",
    "HeuristicConfigCreate",
    "HeuristicConfigResponse",
    "HeuristicConfigListResponse",
    "ActivateConfigRequest",
    "MovementRuleResponse",
    "SettingsMovementRuleCreate",
    "MovementRuleUpdate",
    "EnjoyableActivityResponse",
    "SettingsEnjoyableActivityCreate",
    "EnjoyableActivityUpdate",
]
