"""add_discipline_experience_and_goals

Revision ID: 4fdc46c38149
Revises: 1a2b3c4d5e6f
Create Date: 2026-01-19 11:53:46.342010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdc46c38149'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('discipline_experience', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('long_term_goal_category', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('long_term_goal_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'long_term_goal_description')
    op.drop_column('user_profiles', 'long_term_goal_category')
    op.drop_column('user_profiles', 'discipline_experience')
    # ### end Alembic commands ###
