"""Add visibility and template flags

Revision ID: 6180f4706b14
Revises: 95e6d757f1a4
Create Date: 2026-01-16 00:11:20.123467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6180f4706b14'
down_revision: Union[str, Sequence[str], None] = '95e6d757f1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Define enum type for column definition
    visibility_enum = sa.Enum('PRIVATE', 'FRIENDS', 'PUBLIC', name='visibility')
    
    # SQLite doesn't support CREATE TYPE, so we skip explicit enum creation
    # The Enum type in add_column will be handled as VARCHAR by SQLAlchemy on SQLite

    op.add_column('programs', sa.Column('is_template', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('programs', sa.Column('visibility', visibility_enum, nullable=False, server_default='PRIVATE'))
    op.add_column('workout_logs', sa.Column('visibility', visibility_enum, nullable=False, server_default='PRIVATE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'visibility')
    op.drop_column('programs', 'visibility')
    op.drop_column('programs', 'is_template')
    # ### end Alembic commands ###
