"""Schema update for db revamp

Revision ID: 662e6fe73056
Revises: c17d36fd7214
Create Date: 2026-01-23 00:09:19.378771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662e6fe73056'
down_revision: Union[str, Sequence[str], None] = 'c17d36fd7214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Helper to create enum if not exists
    bind = op.get_bind()
    def create_enum_if_not_exists(name, values):
        if bind.dialect.name == 'postgresql':
            values_str = ", ".join(f"'{v}'" for v in values)
            op.execute(sa.text(f"""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{name}') THEN
                    CREATE TYPE {name} AS ENUM ({values_str});
                END IF;
            END$$;
            """))
    
    create_enum_if_not_exists('relationshiptype', ['progression', 'regression', 'variation', 'antagonist', 'prep'])
    create_enum_if_not_exists('spinalcompression', ['none', 'low', 'moderate', 'high'])
    
    # Handle Enum Mismatches (Uppercase in DB vs Lowercase in App)
    # Rename old uppercase enums if they exist so we can create new lowercase ones
    op.execute("""
    DO $$
    BEGIN
        -- Fix movementpattern (UPPER -> lower)
        IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'movementpattern') THEN
            IF EXISTS (SELECT 1 FROM pg_enum JOIN pg_type ON pg_enum.enumtypid = pg_type.oid WHERE pg_type.typname = 'movementpattern' AND pg_enum.enumlabel = 'SQUAT') THEN
                ALTER TYPE movementpattern RENAME TO movementpattern_old;
            END IF;
        END IF;

        -- Fix metrictype (UPPER -> lower)
        IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'metrictype') THEN
            IF EXISTS (SELECT 1 FROM pg_enum JOIN pg_type ON pg_enum.enumtypid = pg_type.oid WHERE pg_type.typname = 'metrictype' AND pg_enum.enumlabel = 'REPS') THEN
                ALTER TYPE metrictype RENAME TO metrictype_old;
            END IF;
        END IF;

        -- Fix experiencelevel (UPPER -> lower)
        IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'experiencelevel') THEN
             IF EXISTS (SELECT 1 FROM pg_enum JOIN pg_type ON pg_enum.enumtypid = pg_type.oid WHERE pg_type.typname = 'experiencelevel' AND pg_enum.enumlabel = 'BEGINNER') THEN
                ALTER TYPE experiencelevel RENAME TO experiencelevel_old;
            END IF;
        END IF;
    END$$;
    """)

    create_enum_if_not_exists('movementpattern', ['squat', 'hinge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'carry', 'core', 'lunge', 'rotation', 'plyometric', 'olympic', 'isolation', 'mobility', 'isometric', 'conditioning', 'cardio'])
    create_enum_if_not_exists('primarymuscle', ['quadriceps', 'hamstrings', 'glutes', 'calves', 'chest', 'lats', 'upper_back', 'rear_delts', 'front_delts', 'side_delts', 'biceps', 'triceps', 'forearms', 'core', 'obliques', 'lower_back', 'hip_flexors', 'adductors', 'full_body'])
    # Use spaces to match DB and App definition
    create_enum_if_not_exists('primaryregion', ['anterior lower', 'posterior lower', 'shoulder', 'anterior upper', 'posterior upper', 'full body', 'lower body', 'upper body'])
    create_enum_if_not_exists('cnsload', ['very_low', 'low', 'moderate', 'high', 'very_high'])
    create_enum_if_not_exists('skilllevel', ['beginner', 'intermediate', 'advanced', 'expert', 'elite'])
    create_enum_if_not_exists('metrictype', ['reps', 'time', 'time_under_tension', 'distance'])
    create_enum_if_not_exists('ruleoperator', ['eq', 'gt', 'lt', 'lte', 'gte'])
    create_enum_if_not_exists('experiencelevel', ['beginner', 'intermediate', 'advanced', 'expert'])
    create_enum_if_not_exists('sessionsection', ['warmup', 'main', 'accessory', 'finisher', 'cooldown', 'cardio', 'conditioning'])
    
    # Ensure disciplinetype is created with lowercase values
    create_enum_if_not_exists('disciplinetype', ['powerlifting', 'olympic_weightlifting', 'bodybuilding', 'crossfit', 'strongman', 'calisthenics', 'yoga', 'running', 'other'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('movement_coaching_cues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('cue_text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_coaching_cues_movement_id'), 'movement_coaching_cues', ['movement_id'], unique=False)
    op.create_table('movement_disciplines',
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('discipline', postgresql.ENUM('powerlifting', 'olympic_weightlifting', 'bodybuilding', 'crossfit', 'strongman', 'calisthenics', 'yoga', 'running', 'other', name='disciplinetype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.PrimaryKeyConstraint('movement_id', 'discipline')
    )
    op.create_index(op.f('ix_movement_disciplines_discipline'), 'movement_disciplines', ['discipline'], unique=False)
    op.create_table('movement_equipment',
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.PrimaryKeyConstraint('movement_id', 'equipment_id')
    )
    op.create_table('movement_tags',
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('movement_id', 'tag_id')
    )
    op.alter_column('movement_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('progression', 'regression', 'variation', 'antagonist', 'prep', name='relationshiptype', create_type=False),
               existing_nullable=False,
               postgresql_using="LOWER(relationship_type)::relationshiptype")
    op.add_column('movements', sa.Column('spinal_compression', sa.Enum('none', 'low', 'moderate', 'high', name='spinalcompression', create_type=False), nullable=False, server_default='none'))
    
    # Handle movementpattern migration (might be Uppercase in DB, converting to Lowercase)
    # If it exists as Uppercase, we might need to recreate it. 
    # But for now, let's try assuming we can cast to it.
    # If the existing type is Uppercase, LOWER(pattern)::movementpattern will fail.
    # So we should probably force create the lowercase type if we can, or rely on postgresql_using to handle it if we renamed the old type.
    # Given the complexity, and that I saw it was Uppercase in DB, I will assume we want to keep it Uppercase OR the user wants consistency.
    # I will stick to Lowercase consistency. 
    op.alter_column('movements', 'pattern',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('squat', 'hinge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'carry', 'core', 'lunge', 'rotation', 'plyometric', 'olympic', 'isolation', 'mobility', 'isometric', 'conditioning', 'cardio', name='movementpattern', create_type=False),
               existing_nullable=False,
               postgresql_using="LOWER(REPLACE(pattern, ' ', '_'))::movementpattern")
    
    op.alter_column('movements', 'primary_muscle',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('quadriceps', 'hamstrings', 'glutes', 'calves', 'chest', 'lats', 'upper_back', 'rear_delts', 'front_delts', 'side_delts', 'biceps', 'triceps', 'forearms', 'core', 'obliques', 'lower_back', 'hip_flexors', 'adductors', 'full_body', name='primarymuscle', create_type=False),
               existing_nullable=False,
               postgresql_using="LOWER(primary_muscle)::primarymuscle")
    op.alter_column('movements', 'primary_region',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('anterior_lower', 'posterior_lower', 'shoulder', 'anterior_upper', 'posterior_upper', 'full_body', 'lower_body', 'upper_body', name='primaryregion', create_type=False),
               existing_nullable=False,
               postgresql_using="LOWER(primary_region)::primaryregion")
    op.alter_column('movements', 'cns_load',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('very_low', 'low', 'moderate', 'high', 'very_high', name='cnsload', create_type=False),
               existing_nullable=False,
               postgresql_using="LOWER(cns_load)::cnsload")
    op.alter_column('movements', 'skill_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('beginner', 'intermediate', 'advanced', 'expert', 'elite', name='skilllevel', create_type=False),
               existing_nullable=False,
               postgresql_using="LOWER(skill_level)::skilllevel")
    op.alter_column('movements', 'metric_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('reps', 'time', 'time_under_tension', 'distance', name='metrictype', create_type=False),
               existing_nullable=False,
               postgresql_using="LOWER(REPLACE(metric_type, ' ', '_'))::metrictype")
    # op.drop_column('movements', 'tags')
    # op.drop_column('movements', 'primary_discipline')
    # op.drop_column('movements', 'equipment_tags')
    # op.drop_column('movements', 'secondary_muscles')
    # op.drop_column('movements', 'discipline_tags')
    # op.drop_column('movements', 'coaching_cues')
    op.add_column('muscles', sa.Column('stimulus_coefficient', sa.Float(), nullable=False))
    op.add_column('muscles', sa.Column('fatigue_coefficient', sa.Float(), nullable=False))
    op.alter_column('muscles', 'region',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('anterior lower', 'posterior lower', 'shoulder', 'anterior upper', 'posterior upper', 'full body', 'lower body', 'upper body', name='primaryregion', create_type=False),
               existing_nullable=True,
               postgresql_using="LOWER(region)::primaryregion")
    op.add_column('session_exercises', sa.Column('session_section', sa.Enum('warmup', 'main', 'accessory', 'finisher', 'cooldown', 'cardio', 'conditioning', name='sessionsection', create_type=False), nullable=False))
    op.add_column('session_exercises', sa.Column('circuit_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_session_exercises_circuit_id'), 'session_exercises', ['circuit_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_session_section'), 'session_exercises', ['session_section'], unique=False)
    op.create_foreign_key(None, 'session_exercises', 'circuit_templates', ['circuit_id'], ['id'])
    # op.drop_column('sessions', 'warmup_json')
    # op.drop_column('sessions', 'accessory_json')
    # op.drop_column('sessions', 'main_json')
    # op.drop_column('sessions', 'finisher_json')
    # op.drop_column('sessions', 'cooldown_json')
    op.add_column('user_movement_rules', sa.Column('rule_operator', sa.Enum('eq', 'gt', 'lt', 'lte', 'gte', name='ruleoperator', create_type=False), nullable=False, server_default='eq'))
    # op.drop_column('user_movement_rules', 'notes')
    op.add_column('user_skills', sa.Column('interest_level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('macro_experience_level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='experiencelevel', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'macro_experience_level')
    op.drop_column('user_skills', 'interest_level')
    # op.add_column('user_movement_rules', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_movement_rules', 'rule_operator')
    # op.add_column('sessions', sa.Column('cooldown_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.add_column('sessions', sa.Column('finisher_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.add_column('sessions', sa.Column('main_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.add_column('sessions', sa.Column('accessory_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.add_column('sessions', sa.Column('warmup_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('session_exercises_circuit_id_fkey', 'session_exercises', type_='foreignkey')
    op.drop_index(op.f('ix_session_exercises_session_section'), table_name='session_exercises')
    op.drop_index(op.f('ix_session_exercises_circuit_id'), table_name='session_exercises')
    op.drop_column('session_exercises', 'circuit_id')
    op.drop_column('session_exercises', 'session_section')
    op.alter_column('muscles', 'region',
               existing_type=sa.Enum('anterior_lower', 'posterior_lower', 'shoulder', 'anterior_upper', 'posterior_upper', 'full_body', 'lower_body', 'upper_body', name='primaryregion'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('muscles', 'fatigue_coefficient')
    op.drop_column('muscles', 'stimulus_coefficient')
    # op.add_column('movements', sa.Column('coaching_cues', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.add_column('movements', sa.Column('discipline_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.add_column('movements', sa.Column('secondary_muscles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.add_column('movements', sa.Column('equipment_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.add_column('movements', sa.Column('primary_discipline', sa.VARCHAR(length=50), server_default=sa.text("'All'::character varying"), autoincrement=False, nullable=False))
    # op.add_column('movements', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.alter_column('movements', 'metric_type',
               existing_type=sa.Enum('reps', 'time', 'time_under_tension', 'distance', name='metrictype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('movements', 'skill_level',
               existing_type=sa.Enum('beginner', 'intermediate', 'advanced', 'expert', 'elite', name='skilllevel'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('movements', 'cns_load',
               existing_type=sa.Enum('very_low', 'low', 'moderate', 'high', 'very_high', name='cnsload'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('movements', 'primary_region',
               existing_type=sa.Enum('anterior_lower', 'posterior_lower', 'shoulder', 'anterior_upper', 'posterior_upper', 'full_body', 'lower_body', 'upper_body', name='primaryregion'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('movements', 'primary_muscle',
               existing_type=sa.Enum('quadriceps', 'hamstrings', 'glutes', 'calves', 'chest', 'lats', 'upper_back', 'rear_delts', 'front_delts', 'side_delts', 'biceps', 'triceps', 'forearms', 'core', 'obliques', 'lower_back', 'hip_flexors', 'adductors', 'full_body', name='primarymuscle'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('movements', 'pattern',
               existing_type=sa.Enum('squat', 'hinge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'carry', 'core', 'lunge', 'rotation', 'plyometric', 'olympic', 'isolation', 'mobility', 'isometric', 'conditioning', 'cardio', name='movementpattern'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('movements', 'spinal_compression')
    op.alter_column('movement_relationships', 'relationship_type',
               existing_type=sa.Enum('progression', 'regression', 'variation', 'antagonist', 'prep', name='relationshiptype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('movement_tags')
    op.drop_table('movement_equipment')
    op.drop_index(op.f('ix_movement_disciplines_discipline'), table_name='movement_disciplines')
    op.drop_table('movement_disciplines')
    op.drop_index(op.f('ix_movement_coaching_cues_movement_id'), table_name='movement_coaching_cues')
    op.drop_table('movement_coaching_cues')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
