"""add name to programs

Revision ID: 87ec9db39e1e
Revises: f7b2ea3f26c9
Create Date: 2026-01-16 23:40:34.989154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ec9db39e1e'
down_revision: Union[str, Sequence[str], None] = 'f7b2ea3f26c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'name')
    # ### end Alembic commands ###
