"""Initial migration

Revision ID: 95e6d757f1a4
Revises: 
Create Date: 2026-01-15 22:33:50.497916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e6d757f1a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heuristic_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('json_blob', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heuristic_configs_active'), 'heuristic_configs', ['active'], unique=False)
    op.create_index(op.f('ix_heuristic_configs_name'), 'heuristic_configs', ['name'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=False),
    sa.Column('primary_muscle', sa.String(length=50), nullable=False),
    sa.Column('primary_region', sa.String(length=50), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=True),
    sa.Column('cns_load', sa.String(length=50), nullable=False),
    sa.Column('skill_level', sa.String(length=50), nullable=False),
    sa.Column('compound', sa.Boolean(), nullable=True),
    sa.Column('is_complex_lift', sa.Boolean(), nullable=True),
    sa.Column('is_unilateral', sa.Boolean(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('discipline_tags', sa.JSON(), nullable=True),
    sa.Column('equipment_tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coaching_cues', sa.JSON(), nullable=True),
    sa.Column('substitution_group', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_name'), 'movements', ['name'], unique=True)
    op.create_index(op.f('ix_movements_pattern'), 'movements', ['pattern'], unique=False)
    op.create_index(op.f('ix_movements_primary_muscle'), 'movements', ['primary_muscle'], unique=False)
    op.create_index(op.f('ix_movements_primary_region'), 'movements', ['primary_region'], unique=False)
    op.create_index(op.f('ix_movements_substitution_group'), 'movements', ['substitution_group'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='experiencelevel'), nullable=False),
    sa.Column('persona_tone', sa.Enum('DRILL_SERGEANT', 'SUPPORTIVE', 'ANALYTICAL', 'MOTIVATIONAL', 'MINIMALIST', name='personatone'), nullable=False),
    sa.Column('persona_aggression', sa.Enum('CONSERVATIVE', 'MODERATE_CONSERVATIVE', 'BALANCED', 'MODERATE_AGGRESSIVE', 'AGGRESSIVE', name='personaaggression'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('goal_1', sa.Enum('STRENGTH', 'HYPERTROPHY', 'ENDURANCE', 'FAT_LOSS', 'MOBILITY', 'EXPLOSIVENESS', 'SPEED', name='goal'), nullable=False),
    sa.Column('goal_2', sa.Enum('STRENGTH', 'HYPERTROPHY', 'ENDURANCE', 'FAT_LOSS', 'MOBILITY', 'EXPLOSIVENESS', 'SPEED', name='goal'), nullable=False),
    sa.Column('goal_3', sa.Enum('STRENGTH', 'HYPERTROPHY', 'ENDURANCE', 'FAT_LOSS', 'MOBILITY', 'EXPLOSIVENESS', 'SPEED', name='goal'), nullable=False),
    sa.Column('goal_weight_1', sa.Integer(), nullable=False),
    sa.Column('goal_weight_2', sa.Integer(), nullable=False),
    sa.Column('goal_weight_3', sa.Integer(), nullable=False),
    sa.Column('split_template', sa.Enum('UPPER_LOWER', 'PPL', 'FULL_BODY', 'HYBRID', name='splittemplate'), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('progression_style', sa.Enum('SINGLE_PROGRESSION', 'DOUBLE_PROGRESSION', 'PAUSED_VARIATIONS', 'BUILD_TO_DROP', name='progressionstyle'), nullable=False),
    sa.Column('hybrid_definition', sa.JSON(), nullable=True),
    sa.Column('disciplines_json', sa.JSON(), nullable=True),
    sa.Column('deload_every_n_microcycles', sa.Integer(), nullable=False),
    sa.Column('persona_tone', sa.Enum('DRILL_SERGEANT', 'SUPPORTIVE', 'ANALYTICAL', 'MOTIVATIONAL', 'MINIMALIST', name='personatone'), nullable=False),
    sa.Column('persona_aggression', sa.Enum('CONSERVATIVE', 'MODERATE_CONSERVATIVE', 'BALANCED', 'MODERATE_AGGRESSIVE', 'AGGRESSIVE', name='personaaggression'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('duration_weeks >= 8 AND duration_weeks <= 12', name='valid_duration'),
    sa.CheckConstraint('goal_weight_1 + goal_weight_2 + goal_weight_3 = 10', name='goals_sum_to_ten'),
    sa.CheckConstraint('goal_weight_1 >= 0 AND goal_weight_2 >= 0 AND goal_weight_3 >= 0', name='positive_weights'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_user_id'), 'programs', ['user_id'], unique=False)
    op.create_table('user_enjoyable_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('TENNIS', 'BOULDERING', 'CYCLING', 'SWIMMING', 'HIKING', 'BASKETBALL', 'FOOTBALL', 'YOGA', 'MARTIAL_ARTS', 'DANCE', 'OTHER', name='enjoyableactivity'), nullable=False),
    sa.Column('custom_name', sa.String(length=100), nullable=True),
    sa.Column('recommend_every_days', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_enjoyable_activities_user_id'), 'user_enjoyable_activities', ['user_id'], unique=False)
    op.create_table('user_movement_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('HARD_NO', 'HARD_YES', 'PREFERRED', name='movementruletype'), nullable=False),
    sa.Column('cadence', sa.Enum('PER_MICROCYCLE', 'WEEKLY', 'BIWEEKLY', name='rulecadence'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_movement_rules_movement_id'), 'user_movement_rules', ['movement_id'], unique=False)
    op.create_index(op.f('ix_user_movement_rules_user_id'), 'user_movement_rules', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active_e1rm_formula', sa.Enum('EPLEY', 'BRZYCKI', 'LOMBARDI', 'OCONNER', name='e1rmformula'), nullable=False),
    sa.Column('use_metric', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('microcycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('length_days', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETE', name='microcyclestatus'), nullable=False),
    sa.Column('is_deload', sa.Boolean(), nullable=True),
    sa.CheckConstraint('length_days >= 7 AND length_days <= 10', name='valid_length'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microcycles_program_id'), 'microcycles', ['program_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('microcycle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('UPPER', 'LOWER', 'PUSH', 'PULL', 'LEGS', 'FULL_BODY', 'CARDIO', 'MOBILITY', 'RECOVERY', 'SKILL', 'CUSTOM', name='sessiontype'), nullable=False),
    sa.Column('intent_tags', sa.JSON(), nullable=True),
    sa.Column('warmup_json', sa.JSON(), nullable=True),
    sa.Column('main_json', sa.JSON(), nullable=True),
    sa.Column('accessory_json', sa.JSON(), nullable=True),
    sa.Column('finisher_json', sa.JSON(), nullable=True),
    sa.Column('cooldown_json', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('warmup_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('main_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('accessory_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('finisher_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cooldown_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['microcycle_id'], ['microcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_date'), 'sessions', ['date'], unique=False)
    op.create_index(op.f('ix_sessions_microcycle_id'), 'sessions', ['microcycle_id'], unique=False)
    op.create_table('conversation_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('context_date', sa.DateTime(), nullable=True),
    sa.Column('context_session_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('final_plan_accepted', sa.Boolean(), nullable=True),
    sa.Column('accepted_plan_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['context_session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_threads_user_id'), 'conversation_threads', ['user_id'], unique=False)
    op.create_table('recovery_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('DUMMY', 'MANUAL', 'GARMIN', 'APPLE', 'AURA_RING', 'WHOOP_BAND', name='recoverysource'), nullable=False),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('readiness', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_signals_date'), 'recovery_signals', ['date'], unique=False)
    op.create_index(op.f('ix_recovery_signals_user_id'), 'recovery_signals', ['user_id'], unique=False)
    op.create_table('session_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('WARMUP', 'MAIN', 'ACCESSORY', 'SKILL', 'FINISHER', 'COOLDOWN', name='exerciserole'), nullable=False),
    sa.Column('order_in_session', sa.Integer(), nullable=False),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_rep_range_min', sa.Integer(), nullable=True),
    sa.Column('target_rep_range_max', sa.Integer(), nullable=True),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('target_rir', sa.Integer(), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=True),
    sa.Column('is_complex_lift', sa.Boolean(), nullable=True),
    sa.Column('substitution_allowed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_exercises_movement_id'), 'session_exercises', ['movement_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_session_id'), 'session_exercises', ['session_id'], unique=False)
    op.create_table('soreness_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=False),
    sa.Column('soreness_1_5', sa.Integer(), nullable=False),
    sa.Column('inferred_cause_session_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inferred_cause_session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soreness_logs_date'), 'soreness_logs', ['date'], unique=False)
    op.create_index(op.f('ix_soreness_logs_user_id'), 'soreness_logs', ['user_id'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('perceived_difficulty', sa.Integer(), nullable=True),
    sa.Column('enjoyment_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_tags', sa.JSON(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_logs_date'), 'workout_logs', ['date'], unique=False)
    op.create_index(op.f('ix_workout_logs_session_id'), 'workout_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_response_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['conversation_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_thread_id'), 'conversation_turns', ['thread_id'], unique=False)
    op.create_table('top_set_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_log_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('avg_rest_seconds', sa.Integer(), nullable=True),
    sa.Column('e1rm_value', sa.Float(), nullable=True),
    sa.Column('e1rm_formula', sa.Enum('EPLEY', 'BRZYCKI', 'LOMBARDI', 'OCONNER', name='e1rmformula'), nullable=True),
    sa.Column('pattern', sa.Enum('SQUAT', 'HINGE', 'HORIZONTAL_PUSH', 'VERTICAL_PUSH', 'HORIZONTAL_PULL', 'VERTICAL_PULL', 'CARRY', 'CORE', 'LUNGE', 'ROTATION', 'PLYOMETRIC', 'OLYMPIC', 'ISOLATION', 'MOBILITY', 'ISOMETRIC', 'CONDITIONING', 'CARDIO', name='movementpattern'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_set_logs_movement_id'), 'top_set_logs', ['movement_id'], unique=False)
    op.create_index(op.f('ix_top_set_logs_pattern'), 'top_set_logs', ['pattern'], unique=False)
    op.create_index(op.f('ix_top_set_logs_workout_log_id'), 'top_set_logs', ['workout_log_id'], unique=False)
    op.create_table('pattern_exposures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('microcycle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pattern', sa.Enum('SQUAT', 'HINGE', 'HORIZONTAL_PUSH', 'VERTICAL_PUSH', 'HORIZONTAL_PULL', 'VERTICAL_PULL', 'CARRY', 'CORE', 'LUNGE', 'ROTATION', 'PLYOMETRIC', 'OLYMPIC', 'ISOLATION', 'MOBILITY', 'ISOMETRIC', 'CONDITIONING', 'CARDIO', name='movementpattern'), nullable=False),
    sa.Column('e1rm_value', sa.Float(), nullable=False),
    sa.Column('source_top_set_log_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['microcycle_id'], ['microcycles.id'], ),
    sa.ForeignKeyConstraint(['source_top_set_log_id'], ['top_set_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_exposures_date'), 'pattern_exposures', ['date'], unique=False)
    op.create_index(op.f('ix_pattern_exposures_microcycle_id'), 'pattern_exposures', ['microcycle_id'], unique=False)
    op.create_index(op.f('ix_pattern_exposures_pattern'), 'pattern_exposures', ['pattern'], unique=False)
    op.create_index(op.f('ix_pattern_exposures_user_id'), 'pattern_exposures', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_exposures_user_id'), table_name='pattern_exposures')
    op.drop_index(op.f('ix_pattern_exposures_pattern'), table_name='pattern_exposures')
    op.drop_index(op.f('ix_pattern_exposures_microcycle_id'), table_name='pattern_exposures')
    op.drop_index(op.f('ix_pattern_exposures_date'), table_name='pattern_exposures')
    op.drop_table('pattern_exposures')
    op.drop_index(op.f('ix_top_set_logs_workout_log_id'), table_name='top_set_logs')
    op.drop_index(op.f('ix_top_set_logs_pattern'), table_name='top_set_logs')
    op.drop_index(op.f('ix_top_set_logs_movement_id'), table_name='top_set_logs')
    op.drop_table('top_set_logs')
    op.drop_index(op.f('ix_conversation_turns_thread_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_session_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_date'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_soreness_logs_user_id'), table_name='soreness_logs')
    op.drop_index(op.f('ix_soreness_logs_date'), table_name='soreness_logs')
    op.drop_table('soreness_logs')
    op.drop_index(op.f('ix_session_exercises_session_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_session_exercises_movement_id'), table_name='session_exercises')
    op.drop_table('session_exercises')
    op.drop_index(op.f('ix_recovery_signals_user_id'), table_name='recovery_signals')
    op.drop_index(op.f('ix_recovery_signals_date'), table_name='recovery_signals')
    op.drop_table('recovery_signals')
    op.drop_index(op.f('ix_conversation_threads_user_id'), table_name='conversation_threads')
    op.drop_table('conversation_threads')
    op.drop_index(op.f('ix_sessions_microcycle_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_date'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_microcycles_program_id'), table_name='microcycles')
    op.drop_table('microcycles')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_movement_rules_user_id'), table_name='user_movement_rules')
    op.drop_index(op.f('ix_user_movement_rules_movement_id'), table_name='user_movement_rules')
    op.drop_table('user_movement_rules')
    op.drop_index(op.f('ix_user_enjoyable_activities_user_id'), table_name='user_enjoyable_activities')
    op.drop_table('user_enjoyable_activities')
    op.drop_index(op.f('ix_programs_user_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_table('users')
    op.drop_index(op.f('ix_movements_substitution_group'), table_name='movements')
    op.drop_index(op.f('ix_movements_primary_region'), table_name='movements')
    op.drop_index(op.f('ix_movements_primary_muscle'), table_name='movements')
    op.drop_index(op.f('ix_movements_pattern'), table_name='movements')
    op.drop_index(op.f('ix_movements_name'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_heuristic_configs_name'), table_name='heuristic_configs')
    op.drop_index(op.f('ix_heuristic_configs_active'), table_name='heuristic_configs')
    op.drop_table('heuristic_configs')
    # ### end Alembic commands ###
