"""ensemble_coach_schema_updates

Revision ID: bd7af9fae4b9
Revises: 4fdc46c38149
Create Date: 2026-01-19 23:56:43.635653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7af9fae4b9'
down_revision: Union[str, Sequence[str], None] = '4fdc46c38149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_activity_records', sa.Column('distance_meters', sa.Float(), nullable=True))
    op.add_column('external_activity_records', sa.Column('elevation_gain_meters', sa.Float(), nullable=True))
    op.add_column('external_activity_records', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('external_activity_records', sa.Column('average_hr', sa.Integer(), nullable=True))
    op.add_column('external_activity_records', sa.Column('max_hr', sa.Integer(), nullable=True))
    op.add_column('external_activity_records', sa.Column('average_watts', sa.Integer(), nullable=True))
    op.add_column('external_activity_records', sa.Column('device_name', sa.String(length=100), nullable=True))
    op.add_column('movements', sa.Column('fatigue_factor', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('movements', sa.Column('stimulus_factor', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('movements', sa.Column('injury_risk_factor', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('movements', sa.Column('min_recovery_hours', sa.Integer(), server_default='24', nullable=False))
    
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', 'elite', name='skilllevel'), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skills_discipline_id'), 'user_skills', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)

    op.create_table('user_injuries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_injuries_body_part'), 'user_injuries', ['body_part'], unique=False)
    op.create_index(op.f('ix_user_injuries_user_id'), 'user_injuries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movements', 'min_recovery_hours')
    op.drop_column('movements', 'injury_risk_factor')
    op.drop_column('movements', 'stimulus_factor')
    op.drop_column('movements', 'fatigue_factor')
    op.drop_column('external_activity_records', 'device_name')
    op.drop_column('external_activity_records', 'average_watts')
    op.drop_column('external_activity_records', 'max_hr')
    op.drop_column('external_activity_records', 'average_hr')
    op.drop_column('external_activity_records', 'calories')
    op.drop_column('external_activity_records', 'elevation_gain_meters')
    op.drop_column('external_activity_records', 'distance_meters')
    # ### end Alembic commands ###
