"""add_user_id_columns

Revision ID: c17d36fd7214
Revises: 9dede119032e
Create Date: 2026-01-22 14:45:56.612850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17d36fd7214'
down_revision: Union[str, Sequence[str], None] = '9dede119032e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_session_exercises_user_id'), 'session_exercises', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_session_exercises_user_id'), table_name='session_exercises')
    # ### end Alembic commands ###
