"""add primary_discipline to movements

Revision ID: f7b2ea3f26c9
Revises: b2c3d4e5f6a7
Create Date: 2026-01-16 21:36:37.158295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b2ea3f26c9'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('primary_discipline', sa.String(length=50), server_default='All', nullable=False))
    op.add_column('sessions', sa.Column('main_circuit_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('finisher_circuit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'circuit_templates', ['finisher_circuit_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'circuit_templates', ['main_circuit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'finisher_circuit_id')
    op.drop_column('sessions', 'main_circuit_id')
    op.drop_column('movements', 'primary_discipline')
    # ### end Alembic commands ###
