/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramWizardRouteImport } from './routes/program.wizard'
import { Route as ProgramNewRouteImport } from './routes/program.new'
import { Route as ProgramManualRouteImport } from './routes/program.manual'
import { Route as ProgramProgramIdRouteImport } from './routes/program.$programId'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramWizardRoute = ProgramWizardRouteImport.update({
  id: '/program/wizard',
  path: '/program/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramNewRoute = ProgramNewRouteImport.update({
  id: '/program/new',
  path: '/program/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramManualRoute = ProgramManualRouteImport.update({
  id: '/program/manual',
  path: '/program/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramProgramIdRoute = ProgramProgramIdRouteImport.update({
  id: '/program/$programId',
  path: '/program/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/friends': typeof FriendsRoute
  '/movements': typeof MovementsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/program/$programId': typeof ProgramProgramIdRoute
  '/program/manual': typeof ProgramManualRoute
  '/program/new': typeof ProgramNewRoute
  '/program/wizard': typeof ProgramWizardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/friends': typeof FriendsRoute
  '/movements': typeof MovementsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/program/$programId': typeof ProgramProgramIdRoute
  '/program/manual': typeof ProgramManualRoute
  '/program/new': typeof ProgramNewRoute
  '/program/wizard': typeof ProgramWizardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/friends': typeof FriendsRoute
  '/movements': typeof MovementsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/program/$programId': typeof ProgramProgramIdRoute
  '/program/manual': typeof ProgramManualRoute
  '/program/new': typeof ProgramNewRoute
  '/program/wizard': typeof ProgramWizardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/friends'
    | '/movements'
    | '/settings'
    | '/teams'
    | '/program/$programId'
    | '/program/manual'
    | '/program/new'
    | '/program/wizard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/friends'
    | '/movements'
    | '/settings'
    | '/teams'
    | '/program/$programId'
    | '/program/manual'
    | '/program/new'
    | '/program/wizard'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/friends'
    | '/movements'
    | '/settings'
    | '/teams'
    | '/program/$programId'
    | '/program/manual'
    | '/program/new'
    | '/program/wizard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  FriendsRoute: typeof FriendsRoute
  MovementsRoute: typeof MovementsRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  ProgramProgramIdRoute: typeof ProgramProgramIdRoute
  ProgramManualRoute: typeof ProgramManualRoute
  ProgramNewRoute: typeof ProgramNewRoute
  ProgramWizardRoute: typeof ProgramWizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/wizard': {
      id: '/program/wizard'
      path: '/program/wizard'
      fullPath: '/program/wizard'
      preLoaderRoute: typeof ProgramWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/new': {
      id: '/program/new'
      path: '/program/new'
      fullPath: '/program/new'
      preLoaderRoute: typeof ProgramNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/manual': {
      id: '/program/manual'
      path: '/program/manual'
      fullPath: '/program/manual'
      preLoaderRoute: typeof ProgramManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$programId': {
      id: '/program/$programId'
      path: '/program/$programId'
      fullPath: '/program/$programId'
      preLoaderRoute: typeof ProgramProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  FriendsRoute: FriendsRoute,
  MovementsRoute: MovementsRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  ProgramProgramIdRoute: ProgramProgramIdRoute,
  ProgramManualRoute: ProgramManualRoute,
  ProgramNewRoute: ProgramNewRoute,
  ProgramWizardRoute: ProgramWizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
